-- Sample System Alerts Data for ASF Surveillance System
-- This file contains sample data for the system_alerts table
-- Make sure to import this after creating the system_alerts table

USE asf_surveillance_db;

-- Sample System Alerts
INSERT INTO system_alerts (
    alert_code, 
    alert_type, 
    severity, 
    title, 
    message, 
    related_resource_type, 
    related_resource_id, 
    location_province, 
    location_city, 
    latitude, 
    longitude, 
    status, 
    email_sent, 
    created_by, 
    created_at
) VALUES
-- High Risk Zone Alerts
(
    'ALERT20250101001',
    'high_risk',
    'critical',
    'Critical: High-Risk Zone Detected in Cavite',
    'A high-risk zone has been identified in Cavite Province. Immediate action required. Multiple outbreaks detected within 5km radius. Please implement enhanced surveillance and biosecurity measures.',
    'risk_zone',
    NULL,
    'Cavite',
    'Imus',
    14.4297,
    120.9371,
    'active',
    FALSE,
    1,
    '2025-01-01 08:00:00'
),
(
    'ALERT20250102001',
    'high_risk',
    'high',
    'High-Risk Zone Alert in Laguna',
    'A high-risk zone has been identified in Laguna Province. Enhanced monitoring recommended. Recent outbreak detected in the area. Please ensure proper biosecurity protocols are in place.',
    'risk_zone',
    NULL,
    'Laguna',
    'Calamba',
    14.2116,
    121.1655,
    'active',
    FALSE,
    1,
    '2025-01-02 09:15:00'
),
-- Outbreak Alerts
(
    'ALERT20250103001',
    'outbreak',
    'critical',
    'New ASF Outbreak Confirmed in Batangas',
    'A new ASF outbreak has been confirmed in Batangas Province. Immediate containment measures required. Affected animals: 150 heads. Please coordinate with local authorities for depopulation procedures.',
    'outbreak',
    NULL,
    'Batangas',
    'Bauan',
    13.7919,
    121.0053,
    'active',
    FALSE,
    1,
    '2025-01-03 10:30:00'
),
(
    'ALERT20250104001',
    'outbreak',
    'high',
    'Suspected ASF Outbreak in Rizal',
    'A suspected ASF outbreak has been reported in Rizal Province. Laboratory confirmation pending. Initial reports indicate 50 affected animals. Please proceed with caution and enhanced monitoring.',
    'outbreak',
    NULL,
    'Rizal',
    'Antipolo',
    14.6255,
    121.1245,
    'active',
    FALSE,
    1,
    '2025-01-04 11:45:00'
),
-- Depopulation Alerts
(
    'ALERT20250105001',
    'depopulation',
    'high',
    'Depopulation Event Scheduled in Cavite',
    'A depopulation event is scheduled for January 5, 2025 in Cavite Province. Approximately 200 animals will be depopulated. Please ensure all protocols are followed and compensation procedures are in place.',
    'depopulation',
    NULL,
    'Cavite',
    'Bacoor',
    14.4584,
    120.9425,
    'active',
    FALSE,
    1,
    '2025-01-05 07:00:00'
),
(
    'ALERT20250106001',
    'depopulation',
    'medium',
    'Depopulation Completed in Laguna',
    'Depopulation event successfully completed in Laguna Province. Total animals depopulated: 120 heads. Compensation procedures are ongoing. Enhanced surveillance recommended for the surrounding areas.',
    'depopulation',
    NULL,
    'Laguna',
    'San Pedro',
    14.3595,
    121.0473,
    'resolved',
    FALSE,
    1,
    '2025-01-06 14:20:00'
),
-- Meat Movement Alerts
(
    'ALERT20250107001',
    'meat_movement',
    'high',
    'Unauthorized Meat Movement Detected',
    'Unauthorized meat movement has been detected between Cavite and Laguna provinces. Health certificate verification required. Please investigate and ensure compliance with movement restrictions.',
    'meat_movement',
    NULL,
    'Cavite',
    'Dasmarinas',
    14.3294,
    120.9367,
    'active',
    FALSE,
    1,
    '2025-01-07 09:30:00'
),
(
    'ALERT20250108001',
    'meat_movement',
    'medium',
    'High Volume Meat Movement in Quezon',
    'High volume meat movement detected in Quezon Province. Verification of health certificates recommended. Please ensure all movement records are properly documented.',
    'meat_movement',
    NULL,
    'Quezon',
    'Lucena',
    13.9314,
    121.6174,
    'active',
    FALSE,
    1,
    '2025-01-08 10:15:00'
),
-- Predictive Alerts
(
    'ALERT20250109001',
    'predictive',
    'high',
    'Predictive Model: High Outbreak Risk Forecast',
    'Predictive model indicates high outbreak risk in selected areas of CALABARZON. Environmental factors and historical data suggest increased probability of ASF outbreaks in the next 7 days. Enhanced surveillance recommended.',
    'predictive_model',
    NULL,
    'CALABARZON',
    NULL,
    NULL,
    NULL,
    'active',
    FALSE,
    1,
    '2025-01-09 08:00:00'
),
(
    'ALERT20250110001',
    'predictive',
    'medium',
    'Predictive Model: Moderate Risk Alert',
    'Predictive model indicates moderate outbreak risk in certain areas. Environmental conditions and movement patterns suggest potential risk. Regular monitoring recommended.',
    'predictive_model',
    NULL,
    'CALABARZON',
    NULL,
    NULL,
    NULL,
    'active',
    FALSE,
    1,
    '2025-01-10 09:30:00'
),
-- System Alerts
(
    'ALERT20250111001',
    'system',
    'low',
    'System Maintenance Scheduled',
    'Scheduled system maintenance will occur on January 15, 2025 from 2:00 AM to 4:00 AM. The system may be temporarily unavailable during this time. Please save your work beforehand.',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'active',
    FALSE,
    1,
    '2025-01-11 10:00:00'
),
(
    'ALERT20250112001',
    'system',
    'medium',
    'Database Backup Completed',
    'Daily database backup has been successfully completed. All system data has been backed up and secured. Backup location: secure server.',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'acknowledged',
    FALSE,
    1,
    '2025-01-12 02:30:00'
),
-- Additional High Risk Alerts
(
    'ALERT20250113001',
    'high_risk',
    'critical',
    'Critical: Multiple High-Risk Zones in Batangas',
    'Multiple high-risk zones have been identified in Batangas Province. Immediate coordinated response required. Risk assessment indicates elevated threat level. Please activate emergency protocols.',
    'risk_zone',
    NULL,
    'Batangas',
    'Lipa',
    13.9411,
    121.1631,
    'active',
    FALSE,
    1,
    '2025-01-13 08:45:00'
),
(
    'ALERT20250114001',
    'high_risk',
    'high',
    'High-Risk Zone Alert in Quezon',
    'A high-risk zone has been identified in Quezon Province. Recent activity detected. Enhanced monitoring and biosecurity measures recommended for surrounding areas.',
    'risk_zone',
    NULL,
    'Quezon',
    'Tayabas',
    14.0294,
    121.5925,
    'active',
    FALSE,
    1,
    '2025-01-14 09:20:00'
),
-- Additional Outbreak Alerts
(
    'ALERT20250115001',
    'outbreak',
    'critical',
    'New Outbreak Confirmed in Cavite - Second Location',
    'A second ASF outbreak has been confirmed in Cavite Province. This is in addition to the previous outbreak. Total affected animals across both locations: 300 heads. Coordinated response required.',
    'outbreak',
    NULL,
    'Cavite',
    'Silang',
    14.2306,
    120.9753,
    'active',
    FALSE,
    1,
    '2025-01-15 11:00:00'
),
(
    'ALERT20250116001',
    'outbreak',
    'medium',
    'Outbreak Contained in Rizal',
    'Previous outbreak in Rizal Province has been successfully contained. No new cases reported in the past 7 days. Surveillance continues. Status changed to contained.',
    'outbreak',
    NULL,
    'Rizal',
    'Antipolo',
    14.6255,
    121.1245,
    'resolved',
    FALSE,
    1,
    '2025-01-16 15:30:00'
);
