<?php
/**
 * Reports Management Page
 * Generate and download reports for ASF Surveillance System
 */

require_once '../includes/session_manager.php';
require_once '../config/database.php';

// Check if user is logged in
if (!isLoggedIn()) {
    header('Location: ../login.php');
    exit();
}

// Get current user
$currentUser = getCurrentUser();

// Check if user has permission to view reports
// All authenticated users can view reports, but only admins can generate certain reports
$canGenerateReports = in_array($currentUser['role'], ['administrator', 'supervisor', 'analyst']);

// Set page title
$pageTitle = 'Reports';

// Include header
include 'includes/head.php';
include 'includes/header.php';
include 'includes/sidebar.php';
?>

<main id="main" class="main">
  <div class="pagetitle">
    <h1>Reports</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="index.php">Home</a></li>
        <li class="breadcrumb-item active">Reports</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section">
    <div class="row">
      <div class="col-lg-12">
        
        <!-- Report Generation Card -->
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Generate Report</h5>
            
            <form id="reportForm" class="row g-3">
              <div class="col-md-4">
                <label for="reportType" class="form-label">Report Type <span class="text-danger">*</span></label>
                <select class="form-select" id="reportType" required>
                  <option value="">Select Report Type</option>
                  <option value="outbreaks">ASF Outbreaks</option>
                  <option value="depopulation">Depopulation Events</option>
                  <option value="meat_movement">Meat Movement</option>
                  <option value="environmental">Environmental Data</option>
                  <option value="risk_zones">Risk Zones</option>
                  <option value="predictive_models">Predictive Models</option>
                  <option value="news_articles">News & Announcements</option>
                  <option value="summary">Summary Report (All Data)</option>
                </select>
              </div>
              
              <div class="col-md-3">
                <label for="dateFrom" class="form-label">Date From</label>
                <input type="date" class="form-control" id="dateFrom">
              </div>
              
              <div class="col-md-3">
                <label for="dateTo" class="form-label">Date To</label>
                <input type="date" class="form-control" id="dateTo">
              </div>
              
              <div class="col-md-2">
                <label for="format" class="form-label">Format <span class="text-danger">*</span></label>
                <select class="form-select" id="format" required>
                  <option value="csv">CSV</option>
                  <option value="pdf">PDF</option>
                  <option value="excel">Excel</option>
                </select>
              </div>
              
              <div class="col-12">
                <button type="submit" class="btn btn-primary" id="generateReportBtn">
                  <i class="bi bi-file-earmark-text me-2"></i>Generate Report
                </button>
                <button type="button" class="btn btn-secondary" id="clearFiltersBtn">
                  <i class="bi bi-x-circle me-2"></i>Clear Filters
                </button>
              </div>
            </form>
          </div>
        </div>
        
        <!-- Report History Card -->
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Recent Reports</h5>
            
            <div class="table-responsive">
              <table class="table table-striped table-hover" id="reportsTable">
                <thead>
                  <tr>
                    <th>Report Type</th>
                    <th>Date Range</th>
                    <th>Format</th>
                    <th>Generated By</th>
                    <th>Generated At</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody id="reportsTableBody">
                  <tr>
                    <td colspan="6" class="text-center text-muted">No reports generated yet. Generate a report to see it here.</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </section>
</main><!-- End #main -->

<style>
  .spin {
    animation: spin 1s linear infinite;
  }
  
  @keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
  }
  
  #reportForm {
    margin-bottom: 0;
  }
  
  .table-responsive {
    max-height: 600px;
    overflow-y: auto;
  }
</style>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const reportForm = document.getElementById('reportForm');
    const generateReportBtn = document.getElementById('generateReportBtn');
    const clearFiltersBtn = document.getElementById('clearFiltersBtn');
    const reportsTableBody = document.getElementById('reportsTableBody');
    
    // Load recent reports on page load
    loadRecentReports();
    
    // Generate report
    reportForm.addEventListener('submit', function(e) {
      e.preventDefault();
      generateReport();
    });
    
    // Clear filters
    clearFiltersBtn.addEventListener('click', function() {
      reportForm.reset();
      document.getElementById('reportType').value = '';
      document.getElementById('format').value = 'csv';
    });
    
    // Generate report function
    function generateReport() {
      const reportType = document.getElementById('reportType').value;
      const dateFrom = document.getElementById('dateFrom').value;
      const dateTo = document.getElementById('dateTo').value;
      const format = document.getElementById('format').value;
      
      if (!reportType || !format) {
        alert('Please select report type and format');
        return;
      }
      
      // Validate date range
      if (dateFrom && dateTo && new Date(dateFrom) > new Date(dateTo)) {
        alert('Date From must be before Date To');
        return;
      }
      
      // Show loading state
      const originalText = generateReportBtn.innerHTML;
      generateReportBtn.disabled = true;
      generateReportBtn.innerHTML = '<i class="bi bi-arrow-clockwise spin me-2"></i>Generating...';
      
      // Build URL with parameters
      let url = `ajax/generate_report.php?type=${encodeURIComponent(reportType)}&format=${encodeURIComponent(format)}`;
      if (dateFrom) url += `&date_from=${encodeURIComponent(dateFrom)}`;
      if (dateTo) url += `&date_to=${encodeURIComponent(dateTo)}`;
      
      // Create a temporary link to trigger download
      const link = document.createElement('a');
      link.href = url;
      link.style.display = 'none';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      // Reset button after a delay
      setTimeout(() => {
        generateReportBtn.disabled = false;
        generateReportBtn.innerHTML = originalText;
        loadRecentReports(); // Reload recent reports
      }, 2000);
    }
    
    // Load recent reports
    function loadRecentReports() {
      fetch('ajax/get_recent_reports.php')
        .then(response => response.json())
        .then(data => {
          if (data.success) {
            displayRecentReports(data.reports);
          } else {
            reportsTableBody.innerHTML = '<tr><td colspan="6" class="text-center text-danger">Error loading reports</td></tr>';
          }
        })
        .catch(error => {
          console.error('Error:', error);
          reportsTableBody.innerHTML = '<tr><td colspan="6" class="text-center text-danger">Failed to load reports</td></tr>';
        });
    }
    
    // Display recent reports
    function displayRecentReports(reports) {
      if (reports.length === 0) {
        reportsTableBody.innerHTML = '<tr><td colspan="6" class="text-center text-muted">No reports generated yet</td></tr>';
        return;
      }
      
      reportsTableBody.innerHTML = reports.map(report => {
        const dateRange = report.date_from && report.date_to 
          ? `${report.date_from} to ${report.date_to}`
          : 'All dates';
        const formattedDate = new Date(report.generated_at).toLocaleString();
        
        return `
          <tr>
            <td>${escapeHtml(formatReportType(report.report_type))}</td>
            <td>${dateRange}</td>
            <td><span class="badge bg-info">${report.format.toUpperCase()}</span></td>
            <td>${escapeHtml(report.generated_by || 'N/A')}</td>
            <td>${formattedDate}</td>
            <td>
              <a href="ajax/download_report.php?id=${report.id}" class="btn btn-sm btn-primary" title="Download">
                <i class="bi bi-download"></i>
              </a>
            </td>
          </tr>
        `;
      }).join('');
    }
    
    // Format report type for display
    function formatReportType(type) {
      const types = {
        'outbreaks': 'ASF Outbreaks',
        'depopulation': 'Depopulation Events',
        'meat_movement': 'Meat Movement',
        'environmental': 'Environmental Data',
        'risk_zones': 'Risk Zones',
        'predictive_models': 'Predictive Models',
        'news_articles': 'News & Announcements',
        'summary': 'Summary Report'
      };
      return types[type] || type;
    }
    
    // Escape HTML
    function escapeHtml(text) {
      const div = document.createElement('div');
      div.textContent = text;
      return div.innerHTML;
    }
  });
</script>

<?php
include 'includes/footer.php';
?>
